# Base image
FROM node:20-alpine

WORKDIR /app

COPY coupon-service/package*.json ./
RUN npm install

# Copy source code
COPY coupon-service/ ./

# Build TypeScript
RUN npm run build

# Expose port
EXPOSE 3000

# Start service
CMD ["node", "dist/server.js"]
